java_binary(
    name = "preprocessor",
    srcs = [
        "Preprocessor.java",
        "ReferenceProcessingException.java",
    ],
    deps = [],
    main_class = "preprocessor.Preprocessor",
    visibility = [
        "//visibility:public",
    ]
)
