# Chapter Two homework problems are provided on page 164 of my third-edition copy.

# NOTE: targets that use C's `assert.h` for basic unit testing are `cc_test` targets not `cc_binary`
#       so that we can run `bazel test` on them to check correctness.

cc_binary(
    name = "homework_2_55_to_2_57",
    srcs = ["homework_2_55_to_2_57.c"],
    deps = [],
)

cc_binary(
    name = "homework_2_58",
    srcs = ["homework_2_58.c"],
    deps = [],
)

cc_test(
    name = "homework_2_59",
    srcs = ["homework_2_59.c"],
    deps = [],
)

cc_test(
    name = "homework_2_60",
    srcs = ["homework_2_60.c"],
    deps = [],
)